### PR TITLE
package.json: change "dart-sass" to "sass"

### PR DESCRIPTION
**Pull request by Jimbolino**

### CODE REVIEW

**Comment by sirikon** [comment]
@Jimbolino Some explanation would be appreciated.

Also, the CI is broken.

**Comment by Jimbolino** [comment]
https://github.com/sass/dart-sass/issues/645

tldr: for now they are the same, but "sass" is the preferred one to use

**Comment by sirikon** [comment]
@Jimbolino Thanks for explanation.

 CI still broken. This requires more work than just updating package.json.

**Comment by sirikon** [comment]
Thanks!

**Pull request merged**
